
const works = [
  { file: "01.jpg", title: "IDI 1" },
  { file: "02.jpg", title: "IDI 2" },
  { file: "03.jpg", title: "IDI 3" },
  { file: "04.jpg", title: "IDI 4" },
  { file: "05.jpg", title: "IDI 5" },
  { file: "06.jpg", title: "IDI 6" },
  { file: "07.jpg", title: "IDI 7" },
  { file: "08.jpg", title: "IDI 8" },
  { file: "09.jpg", title: "IDI 9" },
  { file: "10.jpg", title: "IDI 10" },
  { file: "11.jpg", title: "IDI 11" },
  { file: "12.jpg", title: "IDI 12" },
  { file: "13.jpg", title: "IDI 13" },
  { file: "14.jpg", title: "IDI 14" },
  { file: "15.jpg", title: "IDI 15" },
  { file: "16.jpg", title: "IDI 16" },
  { file: "17.jpg", title: "IDI 17" },
  { file: "18.jpg", title: "IDI 18" },
  { file: "19.jpg", title: "IDI 19" },
  { file: "20.jpg", title: "IDI 20" },
  { file: "21.jpg", title: "IDI 21" },
  { file: "22.jpg", title: "IDI 22" },
  { file: "23.jpg", title: "IDI 23" },
  { file: "24.jpg", title: "IDI 24" },
  { file: "25.jpg", title: "IDI 25" },
  { file: "26.jpg", title: "IDI 26" },
  { file: "27.jpg", title: "IDI 27" },
  { file: "28.jpg", title: "IDI 28" },
];
