
const works = [
  { file: "01.jpg", title: "HEYA 1" },
  { file: "02.jpg", title: "HEYA 2" },
  { file: "03.jpg", title: "HEYA 3" },
  { file: "04.jpg", title: "HEYA 4" },
  { file: "05.jpg", title: "HEYA 5" },
  { file: "06.jpg", title: "HEYA 6" },
  { file: "07.jpg", title: "HEYA 7" },
  { file: "08.jpg", title: "HEYA 8" },
  { file: "09.jpg", title: "HEYA 9" },
  { file: "10.jpg", title: "HEYA 10" },
  { file: "11.jpg", title: "HEYA 11" },
  { file: "12.jpg", title: "HEYA 12" },
  { file: "13.jpg", title: "HEYA 13" },
  { file: "14.jpg", title: "HEYA 14" },
  { file: "15.jpg", title: "HEYA 15" },
  { file: "16.jpg", title: "HEYA 16" },
  { file: "17.jpg", title: "HEYA 17" },
  { file: "18.jpg", title: "HEYA 18" },
  { file: "19.jpg", title: "HEYA 19" },
  { file: "20.jpg", title: "HEYA 20" },
  { file: "21.jpg", title: "HEYA 21" },

];
